"""initial schema

Revision ID: 5d849a9b4743
Revises: 
Create Date: 2026-09-06 14:27:22.523985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d849a9b4743'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum_sha256', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('claim_count', sa.Integer(), nullable=False),
    sa.Column('errors_truncated', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batches_checksum_sha256'), 'batches', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_batches_status'), 'batches', ['status'], unique=False)
    op.create_index(op.f('ix_batches_submitted_at'), 'batches', ['submitted_at'], unique=False)
    op.create_table('batch_errors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('row_index', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('field', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_errors_batch_id'), 'batch_errors', ['batch_id'], unique=False)
    op.create_table('claims',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('claimant_name', sa.Text(), nullable=False),
    sa.Column('policy_number', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.Text(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('document_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_batch_id'), 'claims', ['batch_id'], unique=False)
    op.create_index(op.f('ix_claims_claim_type'), 'claims', ['claim_type'], unique=False)
    op.create_index(op.f('ix_claims_external_id'), 'claims', ['external_id'], unique=True)
    op.create_index(op.f('ix_claims_policy_number'), 'claims', ['policy_number'], unique=False)
    op.create_index(op.f('ix_claims_received_at'), 'claims', ['received_at'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_received_at'), table_name='claims')
    op.drop_index(op.f('ix_claims_policy_number'), table_name='claims')
    op.drop_index(op.f('ix_claims_external_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_type'), table_name='claims')
    op.drop_index(op.f('ix_claims_batch_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_batch_errors_batch_id'), table_name='batch_errors')
    op.drop_table('batch_errors')
    op.drop_index(op.f('ix_batches_submitted_at'), table_name='batches')
    op.drop_index(op.f('ix_batches_status'), table_name='batches')
    op.drop_index(op.f('ix_batches_checksum_sha256'), table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
